package com.ichunming.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.uid
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.username
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.code
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.locate_province
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String locateProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.locate_city
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String locateCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sign
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.real_name
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_date
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.update_date
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.uid
     *
     * @return the value of user_info.uid
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.uid
     *
     * @param uid the value for user_info.uid
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.username
     *
     * @return the value of user_info.username
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.username
     *
     * @param username the value for user_info.username
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.code
     *
     * @return the value of user_info.code
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.code
     *
     * @param code the value for user_info.code
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.locate_province
     *
     * @return the value of user_info.locate_province
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getLocateProvince() {
        return locateProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.locate_province
     *
     * @param locateProvince the value for user_info.locate_province
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setLocateProvince(String locateProvince) {
        this.locateProvince = locateProvince == null ? null : locateProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.locate_city
     *
     * @return the value of user_info.locate_city
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getLocateCity() {
        return locateCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.locate_city
     *
     * @param locateCity the value for user_info.locate_city
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setLocateCity(String locateCity) {
        this.locateCity = locateCity == null ? null : locateCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sign
     *
     * @return the value of user_info.sign
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sign
     *
     * @param sign the value for user_info.sign
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.real_name
     *
     * @return the value of user_info.real_name
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.real_name
     *
     * @param realName the value for user_info.real_name
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone
     *
     * @return the value of user_info.phone
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone
     *
     * @param phone the value for user_info.phone
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_date
     *
     * @return the value of user_info.create_date
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_date
     *
     * @param createDate the value for user_info.create_date
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.update_date
     *
     * @return the value of user_info.update_date
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.update_date
     *
     * @param updateDate the value for user_info.update_date
     *
     * @mbggenerated Tue Aug 16 17:42:02 CST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}